### ISSUE TITLE
Just didn't work

### ISSUE THREAD

**Issue by bitsandnumbers** [telega/fever-widget#1]
Hi,

I tried your widget and it sadly didn't work for me. It just shows nothing, no error, no log... I tried several options and were able to reproduce every error supported by the widget, and when I enter the right setup, it just show nothing.

I can actually access my fever instance on my server through different apps with no issue, even hot links, though I can't with this widget. Any idea ?

**Comment by telega** [comment]
Hi,

Thanks for the feedback/issue report. Im going to take another look at it and add some better error messages today to try and figure out whats going wrong. 
Tom

**Comment by telega** [comment]
Hi, 
I have updated the widget. I think the problem was probably in the way I was sending the path of the fever installation. My fever is on a subdomain but probably most people's arent. I hope the new version fixes the problem.
Thanks for submitting the issue!

Tom

**Comment by bitsandnumbers** [comment]
Thanks for the update. My fever installation is on a subdomain too, so the new version didn't work either. I changed the line 12 of the "fever" file to look like this:

`path:'/?api&links',`

Now the links show properly.
Don't you know if it's possible to also display the title of the article the links point to ? It's nice to have surprise but it would be more convenient ;-)

EDIT: ok, as it turns out, I only get the last 2 hotlinks. I tried to add : `&offset=0&range=7&page=1`at the end of the API call, but it changed nothing. It's not a matter of div height either. Do you get the same behavior ?

**Comment by telega** [comment]
It should show the first 20 or so links, with the titles as they appear on the fever web app itself. Im not sure why this isn't happening in your case.

If you can open terminal and navigate to the fever.widget folder (/Library/Application Support/Übersicht/widgets/fever.widget) you can run:
node fever yourfeverinstall.com yourfeverapikey

This should display the whole JSON output from your fever installation, and some other information. You can generate the apikey by running the following line and copying he output into the line above:
echo -n "your@email.com:yourfeverpassword" | md5

Then we can see if the widget is getting the correct information back from your server.
Thanks
Tom

**Comment by bitsandnumbers** [comment]
You're right, I get the exact same output as what your widget gives. Although, I always lack 1 or 2 feed titles from my fever web-app. It must be some error on my setup then…
