### ISSUE TITLE
undefined is not an object (evaluating '_reflength')

### ISSUE THREAD

**Issue by rollecode** [telega/fever-widget#2]
Hi, I love this idea! As a fever user this could be cool. Hovever, on Yosemite, I get this `undefined is not an object (evaluating '_reflength')`. My credentials should be fine.

**Comment by telega** [comment]
Thanks for the feedback. I'll take a look at the issue when I get home next week. Tom

**Comment by telega** [comment]
So, a year later I rewrote the whole widget to give better error information. Apologies.
